version: "3.3"
services:

  jmeter-server-01:
    build: ./images/server-01
    container_name: jmeter-server-01
    networks:
      jmeter:
        ipv4_address: 172.26.0.11

  jmeter-server-02:
    build: ./images/server-02
    container_name: jmeter-server-02
    networks:
      jmeter:
        ipv4_address: 172.26.0.12

  jmeter-client:
    build: ./images/client
    container_name: jmeter-client
    depends_on:
      - jmeter-server-01
      - jmeter-server-02
    volumes:
      - ~/jmeter-docker-volume:/jmeter/bin/results
    networks:
      jmeter:
        ipv4_address: 172.26.0.2

networks:
  jmeter:
    ipam:
      config:
        - subnet: 172.26.0.3/24