version: "3.3"

services:

  jenkins-master:
    image: deliverymind/jenkins-master:2.73.2-slim.1
    container_name: jenkins-master
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-agent:
    build: ./jenkins-agent
    container_name: jenkins-agent

volumes:
  jenkins_home:
    external: true