version: "3.3"

services:

  jenkins-master:
    build: ./jenkins-master
    container_name: jenkins-master
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      jenkins:
        ipv4_address: 172.25.0.20

  jenkins-agent:
    build: ./jenkins-agent
    container_name: jenkins-agent-21
    networks:
      jenkins:
        ipv4_address: 172.25.0.21

volumes:
  jenkins_home:
    external: true

networks:
  jenkins:
    ipam:
      config:
        - subnet: 172.25.0.3/24